os:
  - linux

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

language: cpp

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install cmake;
    fi

script: ./build

